import uuid
from datetime import datetime, date
from sqlalchemy import String, Float, DateTime, Date, JSON, ForeignKey, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.dialects.postgresql import UUID
from app.models.base import Base

class Policy(Base):
    __tablename__ = "policies"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    policy_number: Mapped[str] = mapped_column(String(64), unique=True, index=True)
    holder_name: Mapped[str] = mapped_column(String(255))
    plan_type: Mapped[str] = mapped_column(String(64)) # HMO, PPO, EPO
    effective_date: Mapped[date] = mapped_column(Date)
    expiration_date: Mapped[date] = mapped_column(Date)
    status: Mapped[str] = mapped_column(String(32), default="active")

    document_path: Mapped[str | None] = mapped_column(String(512)) # Path to uploaded PDF
    parsed_markdown: Mapped[str | None] = mapped_column(Text)       # Markdown generated by Docling

    coverages: Mapped[list["PolicyCoverage"]] = relationship("PolicyCoverage", back_populates="policy")

class PolicyCoverage(Base):
    __tablename__ = "policy_coverages"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    policy_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("policies.id"))
    coverage_type: Mapped[str] = mapped_column(String(128))
    covered_services: Mapped[dict] = mapped_column(JSON, default=dict)
    exclusions: Mapped[dict] = mapped_column(JSON, default=dict)
    deductible: Mapped[float] = mapped_column(Float, default=0.0)
    copay: Mapped[float] = mapped_column(Float, default=0.0)
    coinsurance_percent: Mapped[float] = mapped_column(Float, default=0.0)
    out_of_pocket_max: Mapped[float] = mapped_column(Float, default=0.0)
    annual_limit: Mapped[float | None] = mapped_column(Float)

    policy: Mapped["Policy"] = relationship("Policy", back_populates="coverages")
